//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class InterfazActualizarInformacion extends JPanel {
    private JButton btnActualizarInformacion;
    private JTextField nombreMostrar;
    private JTextField apellidosMostrar;
    private JTextField idEpikMostrar;
    private JTextField correoInstitucionalMostrar;
    private JLabel txtNombres;
    private JLabel txtApellidos;
    private JLabel txtIdEpik;
    private JLabel txtCorreoInstitucional;
    private JLabel txtInformacionPersonal;
    private JLabel rolActualizar;
    private JComboBox selectorRol;

    public InterfazActualizarInformacion() {
        //construct preComponents
        String[] selectorRolItems = {"Estudiante", "Monitor", "Administrador"};

        //construct components
        btnActualizarInformacion = new JButton ("Actualizar información");
        nombreMostrar = new JTextField (5);
        apellidosMostrar = new JTextField (5);
        idEpikMostrar = new JTextField (5);
        correoInstitucionalMostrar = new JTextField (5);
        txtNombres = new JLabel ("Nombres");
        txtApellidos = new JLabel ("Apellidos");
        txtIdEpik = new JLabel ("Id de Epik");
        txtCorreoInstitucional = new JLabel ("Correo Institucional");
        txtInformacionPersonal = new JLabel ("Información personal");
        rolActualizar = new JLabel ("Rol");
        selectorRol = new JComboBox (selectorRolItems);

        //adjust size and set layout
        setPreferredSize (new Dimension (946, 571));
        setLayout (null);

        //add components
        add (btnActualizarInformacion);
        add (nombreMostrar);
        add (apellidosMostrar);
        add (idEpikMostrar);
        add (correoInstitucionalMostrar);
        add (txtNombres);
        add (txtApellidos);
        add (txtIdEpik);
        add (txtCorreoInstitucional);
        add (txtInformacionPersonal);
        add (rolActualizar);
        add (selectorRol);

        //set component bounds (only needed by Absolute Positioning)
        btnActualizarInformacion.setBounds (275, 445, 340, 40);
        nombreMostrar.setBounds (160, 85, 200, 30);
        apellidosMostrar.setBounds (160, 130, 200, 30);
        idEpikMostrar.setBounds (160, 175, 200, 30);
        correoInstitucionalMostrar.setBounds (160, 220, 200, 30);
        txtNombres.setBounds (60, 90, 115, 25);
        txtApellidos.setBounds (60, 130, 100, 25);
        txtIdEpik.setBounds (55, 175, 100, 25);
        txtCorreoInstitucional.setBounds (40, 220, 120, 25);
        txtInformacionPersonal.setBounds (45, 25, 130, 25);
        rolActualizar.setBounds (655, 40, 100, 25);
        selectorRol.setBounds (655, 65, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("InterfazActualizarInformación");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new InterfazActualizarInformacion());
        frame.pack();
        frame.setVisible (true);
    }
}
