//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class InterfazInicioSesion extends JPanel {
    private Estudiante usuarioActual;
    private JButton btnCrearCuenta;
    private JButton btnIniciarSesion;
    private JTextField ingresoUsuario;
    private JPasswordField ingresoContraseña;

    public InterfazInicioSesion() {
        //construct components
        btnCrearCuenta = new JButton ("Crear cuenta");
        btnIniciarSesion = new JButton ("Inicio sesión");
        ingresoUsuario = new JTextField (5);
        ingresoContraseña = new JPasswordField (5);

        //Prueba Usuario
        //Estudiante estudiante = new Estudiante("Juan", "Perez", "prueba", 1000, "admin", "Estudiante");
        Monitor estudiante = new Monitor("Pedro", "Ramirez", "pruebaM", 1001, "admin", "Monitor", "Matematicas");
        //Fin prueba usuario

        //adjust size and set layout
        setPreferredSize (new Dimension (1920, 1080));
        setLayout (null);

        //add components
        add (btnCrearCuenta);
        add (btnIniciarSesion);
        add (ingresoUsuario);
        add (ingresoContraseña);

        //set component bounds (only needed by Absolute Positioning)
        btnCrearCuenta.setBounds (800, 465, 340, 40);//315
        btnIniciarSesion.setBounds (800, 410, 340, 40);//260
        ingresoUsuario.setBounds (800, 295, 340, 40);//145
        ingresoContraseña.setBounds (800, 350, 340, 40);//200


        //Evento iniciar sesion
        btnIniciarSesion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String usuario = ingresoUsuario.getText();
                String contraseña = new String(ingresoContraseña.getPassword());

                // Lógica para iniciar sesión 
                if ((usuario.equals(estudiante.getCorreoInstitucional())||usuario.equals(String.valueOf(estudiante.getIdEpik())))&& contraseña.equals(estudiante.getContraseña())) {
                    Estudiante usuarioActual = estudiante;
                    JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso");
                    JFrame frame = new JFrame ("interfazCrearCuenta");
                    frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
                    frame.getContentPane().add (new MainInterfaz(usuarioActual));
                    frame.pack();
                    frame.setVisible (true);
                    ((Window) getRootPane().getParent()).dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
                }
            } 
        });

        //Evento pulsar boton de crear cuenta
        btnCrearCuenta.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame interfazCC = new JFrame ("Crear cuenta");
                //frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
                interfazCC.getContentPane().add (new InterfazCrearCuenta());
                interfazCC.pack();
                interfazCC.setVisible (true);
                ((Window) getRootPane().getParent()).dispose();
            } 
        });
    }
    public void setUsuarioActual(Estudiante usuarioActual) {
        this.usuarioActual = usuarioActual;
    }

    public Estudiante getUsuarioActual() {
        return usuarioActual;
    }
    public static void main(String[] args) {
        JFrame frame = new JFrame ("Inicio de sesión");
        frame.setDefaultCloseOperation (JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add (new InterfazInicioSesion());
        frame.pack();
        frame.setVisible (true);
    }
}
